version: "3.9"

services:
  web:
    # configuration options that are applied at build time
    build:
      # a path to a directory containing a Dockerfile
      context: .
    # express dependency between services
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/employee_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=pwdpwd
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
  db:
    image: postgres:12.6-alpine
    ports:
      - 5432:5432
    volumes:
      - empdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwdpwd
      - POSTGRES_DB=employee_db

volumes:
  empdata:
