DROP TABLE IF EXISTS employees;

CREATE TABLE IF NOT EXISTS employees(
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) DEFAULT NULL,
  last_name VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL
);
